# Generated by Django 4.2.7 on 2023-11-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
    ]
