# Generated by Django 4.2.7 on 2023-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_student_gender_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
